name: Code Coverage

permissions:
  pull-requests: write
  contents: read # Allow actions/checkout


on:
  pull_request:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/pnpm-install

    - name: Run Code Coverage
      run: pnpm run test --watch=false --no-progress --browsers=ChromeHeadless --code-coverage


    - name: Code Coverage Report
      uses: ArtiomTr/jest-coverage-report-action@v2
      if: always()
      id: coverage
      with:
        coverage-file: coverage/portfolio-web/coverage-final.json
        base-coverage-file: coverage/portfolio-web/coverage-final.json
        skip-step: all
        annotations: failed-tests
        output: comment, report-markdown

    - name: Write coverage to Job Summary
      run: echo ${{ steps.coverage.outputs.report }} >> $GITHUB_STEP_SUMMARY

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        message: ${{ steps.coverage.outputs.report }}