name: Code Coverage

permissions:
  pull-requests: write
  contents: read # Allow actions/checkout


on:
  pull_request:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/pnpm-install

    - name: Run Code Coverage
      run: pnpm run test --watch=false --no-progress --browsers=ChromeHeadless --coverage

    - name: Code Coverage Report
      uses:  davelosert/vitest-coverage-report-action@v2
      if: always()
      with:
        json-summary-path: coverage/portfolio-web/coverage-summary.json
        json-final-path: coverage/portfolio-web/coverage-final.json
        vite-config-path: threshold-vite.config.js
        file-coverage-mode: all
        comment-on: pr
