name: Angular Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.0] # See https://angular.dev/reference/versions for versions targeting

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Tests
      run: pnpm run test -- --watch=false --no-progress --browsers=ChromeHeadless --reporters junit

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: Test Report           # Name of the check run which will be created
        path: TESTS-*.xml    # Path to test results
        reporter: java-junit        # Format of test results
