name: Angular Tests

on:
  push:
  pull_request:

jobs:
  units:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/pnpm-install

    - name: Run Tests
      run: pnpm run test --watch=false --no-progress --browsers=ChromiumHeadless --reporters=junit --output-file=junit.xml

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: Test Report           # Name of the check run which will be created
        path: junit.xml    # Path to test results
        reporter: java-junit        # Format of test results
